version: '3.9'
services:
  microservice_grpc1:
    build:
      context: ./add_user_microservice
      dockerfile: Dockerfile
    ports:
      - "9099:9099" # gRPC port
      - "8089:8089" # RESTful port
    volumes:
      - shared-volume:/home
  microservice_admin:
    build:
      context: ./admin_microservice
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./admin_microservice:/usr/share/nginx/html
  microservice_grpc3:
    build:
      context: ./transfer_user_microservice
      dockerfile: Dockerfile
    ports:
      - "9098:9098" # gRPC port
      - "8088:8088" # RESTful port
  microservice_grpc2:
    build:
      context: ./delete_microservice
      dockerfile: Dockerfile
    ports:
      - "9097:9097" # gRPC port
      - "8087:8087" # RESTful port
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
   
    expose:
      - 9091
    ports:
      - '9091:9091'
    volumes:
      - ./data/authelia/config:/config
    environment:
    
      TZ: 'Australia/Melbourne'
  neo4j_db:
    image: neo4j:4.4.19
    container_name: neo4j
    command: neo4j console --verbose
    environment:
      - NEO4J_AUTH=neo4j/12345678
    ports:
      - "7474:7474"  #HTTP port
      - "7687:7687"  #Bolt port
    volumes:
      - ./import:/import
      
volumes:
  shared-volume:
    driver: local




 