// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: rpc_transfert.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To      int64  `protobuf:"varint,1,opt,name=to,proto3" json:"to,omitempty"`
	From    int64  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Methode string `protobuf:"bytes,3,opt,name=methode,proto3" json:"methode,omitempty"`
}

func (x *TransferNode) Reset() {
	*x = TransferNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferNode) ProtoMessage() {}

func (x *TransferNode) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferNode.ProtoReflect.Descriptor instead.
func (*TransferNode) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{0}
}

func (x *TransferNode) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *TransferNode) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *TransferNode) GetMethode() string {
	if x != nil {
		return x.Methode
	}
	return ""
}

type NodeTranfered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To   int64 `protobuf:"varint,1,opt,name=to,proto3" json:"to,omitempty"`
	From int64 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *NodeTranfered) Reset() {
	*x = NodeTranfered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeTranfered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTranfered) ProtoMessage() {}

func (x *NodeTranfered) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTranfered.ProtoReflect.Descriptor instead.
func (*NodeTranfered) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{1}
}

func (x *NodeTranfered) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *NodeTranfered) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

type TestHeadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head int64  `protobuf:"varint,1,opt,name=head,proto3" json:"head,omitempty"`
	Err  string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *TestHeadRequest) Reset() {
	*x = TestHeadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHeadRequest) ProtoMessage() {}

func (x *TestHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHeadRequest.ProtoReflect.Descriptor instead.
func (*TestHeadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{2}
}

func (x *TestHeadRequest) GetHead() int64 {
	if x != nil {
		return x.Head
	}
	return 0
}

func (x *TestHeadRequest) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type TestHeadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TestHeadResponse) Reset() {
	*x = TestHeadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHeadResponse) ProtoMessage() {}

func (x *TestHeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHeadResponse.ProtoReflect.Descriptor instead.
func (*TestHeadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{3}
}

func (x *TestHeadResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListNodes_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListNodes_Request) Reset() {
	*x = ListNodes_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNodes_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodes_Request) ProtoMessage() {}

func (x *ListNodes_Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodes_Request.ProtoReflect.Descriptor instead.
func (*ListNodes_Request) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{4}
}

func (x *ListNodes_Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListNodes_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ListNodes_Response) Reset() {
	*x = ListNodes_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNodes_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodes_Response) ProtoMessage() {}

func (x *ListNodes_Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodes_Response.ProtoReflect.Descriptor instead.
func (*ListNodes_Response) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodes_Response) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListNodesWithRelation_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToChange     int64  `protobuf:"varint,1,opt,name=to_change,json=toChange,proto3" json:"to_change,omitempty"`
	Father       int64  `protobuf:"varint,2,opt,name=father,proto3" json:"father,omitempty"`
	RelationName string `protobuf:"bytes,3,opt,name=relation_name,json=relationName,proto3" json:"relation_name,omitempty"`
}

func (x *ListNodesWithRelation_Request) Reset() {
	*x = ListNodesWithRelation_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNodesWithRelation_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesWithRelation_Request) ProtoMessage() {}

func (x *ListNodesWithRelation_Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesWithRelation_Request.ProtoReflect.Descriptor instead.
func (*ListNodesWithRelation_Request) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesWithRelation_Request) GetToChange() int64 {
	if x != nil {
		return x.ToChange
	}
	return 0
}

func (x *ListNodesWithRelation_Request) GetFather() int64 {
	if x != nil {
		return x.Father
	}
	return 0
}

func (x *ListNodesWithRelation_Request) GetRelationName() string {
	if x != nil {
		return x.RelationName
	}
	return ""
}

type ListNodesWithRelation_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Err   string  `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *ListNodesWithRelation_Response) Reset() {
	*x = ListNodesWithRelation_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNodesWithRelation_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesWithRelation_Response) ProtoMessage() {}

func (x *ListNodesWithRelation_Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesWithRelation_Response.ProtoReflect.Descriptor instead.
func (*ListNodesWithRelation_Response) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{7}
}

func (x *ListNodesWithRelation_Response) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesWithRelation_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{8}
}

func (x *Node) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartNode []*Node `protobuf:"bytes,1,rep,name=start_node,json=startNode,proto3" json:"start_node,omitempty"`
	EndNodes  []*Node `protobuf:"bytes,2,rep,name=end_nodes,json=endNodes,proto3" json:"end_nodes,omitempty"`
}

func (x *DeleteRelationRequest) Reset() {
	*x = DeleteRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationRequest) ProtoMessage() {}

func (x *DeleteRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRelationRequest) GetStartNode() []*Node {
	if x != nil {
		return x.StartNode
	}
	return nil
}

func (x *DeleteRelationRequest) GetEndNodes() []*Node {
	if x != nil {
		return x.EndNodes
	}
	return nil
}

type DeleteRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *DeleteRelationResponse) Reset() {
	*x = DeleteRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationResponse) ProtoMessage() {}

func (x *DeleteRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationResponse.ProtoReflect.Descriptor instead.
func (*DeleteRelationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRelationResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type MoveFromToDirectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromNode int64 `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode   int64 `protobuf:"varint,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
}

func (x *MoveFromToDirectRequest) Reset() {
	*x = MoveFromToDirectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveFromToDirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFromToDirectRequest) ProtoMessage() {}

func (x *MoveFromToDirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFromToDirectRequest.ProtoReflect.Descriptor instead.
func (*MoveFromToDirectRequest) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{11}
}

func (x *MoveFromToDirectRequest) GetFromNode() int64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

func (x *MoveFromToDirectRequest) GetToNode() int64 {
	if x != nil {
		return x.ToNode
	}
	return 0
}

type MoveFromToDirectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *MoveFromToDirectResponse) Reset() {
	*x = MoveFromToDirectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveFromToDirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFromToDirectResponse) ProtoMessage() {}

func (x *MoveFromToDirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFromToDirectResponse.ProtoReflect.Descriptor instead.
func (*MoveFromToDirectResponse) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{12}
}

func (x *MoveFromToDirectResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ParentNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromNode int64 `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
}

func (x *ParentNodeRequest) Reset() {
	*x = ParentNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentNodeRequest) ProtoMessage() {}

func (x *ParentNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentNodeRequest.ProtoReflect.Descriptor instead.
func (*ParentNodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{13}
}

func (x *ParentNodeRequest) GetFromNode() int64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

type ParentNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node []*Node `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	Err  string  `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *ParentNodeResponse) Reset() {
	*x = ParentNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentNodeResponse) ProtoMessage() {}

func (x *ParentNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentNodeResponse.ProtoReflect.Descriptor instead.
func (*ParentNodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{14}
}

func (x *ParentNodeResponse) GetNode() []*Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ParentNodeResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type CreateIndirectRelations_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetNodes []*Node `protobuf:"bytes,1,rep,name=target_nodes,json=targetNodes,proto3" json:"target_nodes,omitempty"`
	EndNodes    []*Node `protobuf:"bytes,2,rep,name=end_nodes,json=endNodes,proto3" json:"end_nodes,omitempty"`
}

func (x *CreateIndirectRelations_Request) Reset() {
	*x = CreateIndirectRelations_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIndirectRelations_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndirectRelations_Request) ProtoMessage() {}

func (x *CreateIndirectRelations_Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndirectRelations_Request.ProtoReflect.Descriptor instead.
func (*CreateIndirectRelations_Request) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{15}
}

func (x *CreateIndirectRelations_Request) GetTargetNodes() []*Node {
	if x != nil {
		return x.TargetNodes
	}
	return nil
}

func (x *CreateIndirectRelations_Request) GetEndNodes() []*Node {
	if x != nil {
		return x.EndNodes
	}
	return nil
}

type CreateIndirectRelations_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CreateIndirectRelations_Response) Reset() {
	*x = CreateIndirectRelations_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIndirectRelations_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndirectRelations_Response) ProtoMessage() {}

func (x *CreateIndirectRelations_Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndirectRelations_Response.ProtoReflect.Descriptor instead.
func (*CreateIndirectRelations_Response) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{16}
}

func (x *CreateIndirectRelations_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type CreateDirectRelations_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetNodes []*Node `protobuf:"bytes,1,rep,name=target_nodes,json=targetNodes,proto3" json:"target_nodes,omitempty"`
	EndNodes    []*Node `protobuf:"bytes,2,rep,name=end_nodes,json=endNodes,proto3" json:"end_nodes,omitempty"`
}

func (x *CreateDirectRelations_Request) Reset() {
	*x = CreateDirectRelations_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDirectRelations_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectRelations_Request) ProtoMessage() {}

func (x *CreateDirectRelations_Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectRelations_Request.ProtoReflect.Descriptor instead.
func (*CreateDirectRelations_Request) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{17}
}

func (x *CreateDirectRelations_Request) GetTargetNodes() []*Node {
	if x != nil {
		return x.TargetNodes
	}
	return nil
}

func (x *CreateDirectRelations_Request) GetEndNodes() []*Node {
	if x != nil {
		return x.EndNodes
	}
	return nil
}

type CreateDirectRelations_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CreateDirectRelations_Response) Reset() {
	*x = CreateDirectRelations_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDirectRelations_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectRelations_Response) ProtoMessage() {}

func (x *CreateDirectRelations_Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectRelations_Response.ProtoReflect.Descriptor instead.
func (*CreateDirectRelations_Response) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{18}
}

func (x *CreateDirectRelations_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type CreateIndirectRelationsSingleToMany_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetNodes []*Node `protobuf:"bytes,1,rep,name=target_nodes,json=targetNodes,proto3" json:"target_nodes,omitempty"`
	EndNode     int64   `protobuf:"varint,2,opt,name=end_node,json=endNode,proto3" json:"end_node,omitempty"`
}

func (x *CreateIndirectRelationsSingleToMany_Request) Reset() {
	*x = CreateIndirectRelationsSingleToMany_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIndirectRelationsSingleToMany_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndirectRelationsSingleToMany_Request) ProtoMessage() {}

func (x *CreateIndirectRelationsSingleToMany_Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndirectRelationsSingleToMany_Request.ProtoReflect.Descriptor instead.
func (*CreateIndirectRelationsSingleToMany_Request) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{19}
}

func (x *CreateIndirectRelationsSingleToMany_Request) GetTargetNodes() []*Node {
	if x != nil {
		return x.TargetNodes
	}
	return nil
}

func (x *CreateIndirectRelationsSingleToMany_Request) GetEndNode() int64 {
	if x != nil {
		return x.EndNode
	}
	return 0
}

type CreateIndirectRelationsSingleToMany_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CreateIndirectRelationsSingleToMany_Response) Reset() {
	*x = CreateIndirectRelationsSingleToMany_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIndirectRelationsSingleToMany_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndirectRelationsSingleToMany_Response) ProtoMessage() {}

func (x *CreateIndirectRelationsSingleToMany_Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndirectRelationsSingleToMany_Response.ProtoReflect.Descriptor instead.
func (*CreateIndirectRelationsSingleToMany_Response) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{20}
}

func (x *CreateIndirectRelationsSingleToMany_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// func GetNodeWithDirectRelationship(driver neo4j.Driver, from_node int) (*Node, error) {
type GetNodeWithDirectRelationship_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromNode int64 `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
}

func (x *GetNodeWithDirectRelationship_Request) Reset() {
	*x = GetNodeWithDirectRelationship_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeWithDirectRelationship_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeWithDirectRelationship_Request) ProtoMessage() {}

func (x *GetNodeWithDirectRelationship_Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeWithDirectRelationship_Request.ProtoReflect.Descriptor instead.
func (*GetNodeWithDirectRelationship_Request) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{21}
}

func (x *GetNodeWithDirectRelationship_Request) GetFromNode() int64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

type GetNodeWithDirectRelationship_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node []*Node `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	Err  string  `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetNodeWithDirectRelationship_Response) Reset() {
	*x = GetNodeWithDirectRelationship_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeWithDirectRelationship_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeWithDirectRelationship_Response) ProtoMessage() {}

func (x *GetNodeWithDirectRelationship_Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeWithDirectRelationship_Response.ProtoReflect.Descriptor instead.
func (*GetNodeWithDirectRelationship_Response) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{22}
}

func (x *GetNodeWithDirectRelationship_Response) GetNode() []*Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *GetNodeWithDirectRelationship_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type RecursionGetNodeWithDicRelation_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromNode int64 `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
}

func (x *RecursionGetNodeWithDicRelation_Request) Reset() {
	*x = RecursionGetNodeWithDicRelation_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecursionGetNodeWithDicRelation_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursionGetNodeWithDicRelation_Request) ProtoMessage() {}

func (x *RecursionGetNodeWithDicRelation_Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursionGetNodeWithDicRelation_Request.ProtoReflect.Descriptor instead.
func (*RecursionGetNodeWithDicRelation_Request) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{23}
}

func (x *RecursionGetNodeWithDicRelation_Request) GetFromNode() int64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

type RecursionGetNodeWithDicRelation_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node []*Node `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	Err  string  `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *RecursionGetNodeWithDicRelation_Response) Reset() {
	*x = RecursionGetNodeWithDicRelation_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfert_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecursionGetNodeWithDicRelation_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursionGetNodeWithDicRelation_Response) ProtoMessage() {}

func (x *RecursionGetNodeWithDicRelation_Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfert_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursionGetNodeWithDicRelation_Response.ProtoReflect.Descriptor instead.
func (*RecursionGetNodeWithDicRelation_Response) Descriptor() ([]byte, []int) {
	return file_rpc_transfert_proto_rawDescGZIP(), []int{24}
}

func (x *RecursionGetNodeWithDicRelation_Response) GetNode() []*Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RecursionGetNodeWithDicRelation_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_rpc_transfert_proto protoreflect.FileDescriptor

var file_rpc_transfert_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4d, 0x0a, 0x0d, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x65, 0x22, 0x34, 0x0a, 0x0e, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x37,
	0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x2a, 0x0a, 0x10, 0x54, 0x65, 0x73, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x13, 0x4c, 0x69, 0x73,
	0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x22, 0x7c, 0x0a, 0x20, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x5f, 0x77,
	0x69, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x66, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x55,
	0x0a, 0x21, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x5f, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x2a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x69, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x2c, 0x0a, 0x18,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x53, 0x0a, 0x1b, 0x4d, 0x6f,
	0x76, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x6f, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x72,
	0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x6f, 0x4e, 0x6f, 0x64, 0x65, 0x22,
	0x30, 0x0a, 0x1c, 0x4d, 0x6f, 0x76, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x6f, 0x5f,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x22, 0x32, 0x0a, 0x13, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x72, 0x6f,
	0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x46, 0x0a, 0x14, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x77, 0x0a,
	0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x65, 0x6e,
	0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x69, 0x6e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x75,
	0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2b, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x25,
	0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x64,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x7a, 0x0a, 0x30, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f,
	0x74, 0x6f, 0x5f, 0x6d, 0x61, 0x6e, 0x79, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x45, 0x0a, 0x31, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x6d,
	0x61, 0x6e, 0x79, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x44,
	0x0a, 0x25, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x4e, 0x6f, 0x64, 0x65, 0x22, 0x58, 0x0a, 0x26, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x57,
	0x69, 0x74, 0x68, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x47,
	0x0a, 0x28, 0x52, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44, 0x69, 0x63, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66,
	0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x5b, 0x0a, 0x29, 0x52, 0x65, 0x63, 0x75, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x44, 0x69, 0x63, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x6f, 0x34, 0x6a, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_transfert_proto_rawDescOnce sync.Once
	file_rpc_transfert_proto_rawDescData = file_rpc_transfert_proto_rawDesc
)

func file_rpc_transfert_proto_rawDescGZIP() []byte {
	file_rpc_transfert_proto_rawDescOnce.Do(func() {
		file_rpc_transfert_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_transfert_proto_rawDescData)
	})
	return file_rpc_transfert_proto_rawDescData
}

var file_rpc_transfert_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rpc_transfert_proto_goTypes = []interface{}{
	(*TransferNode)(nil),                                 // 0: pb.transfer_node
	(*NodeTranfered)(nil),                                // 1: pb.node_tranfered
	(*TestHeadRequest)(nil),                              // 2: pb.TestHeadRequest
	(*TestHeadResponse)(nil),                             // 3: pb.TestHeadResponse
	(*ListNodes_Request)(nil),                            // 4: pb.List_nodes_Request
	(*ListNodes_Response)(nil),                           // 5: pb.List_nodes_Response
	(*ListNodesWithRelation_Request)(nil),                // 6: pb.List_nodes_with_relation_Request
	(*ListNodesWithRelation_Response)(nil),               // 7: pb.List_nodes_with_relation_Response
	(*Node)(nil),                                         // 8: pb.Node
	(*DeleteRelationRequest)(nil),                        // 9: pb.Delete_relation_request
	(*DeleteRelationResponse)(nil),                       // 10: pb.Delete_relation_response
	(*MoveFromToDirectRequest)(nil),                      // 11: pb.Move_from_to_direct_request
	(*MoveFromToDirectResponse)(nil),                     // 12: pb.Move_from_to_direct_response
	(*ParentNodeRequest)(nil),                            // 13: pb.Parent_node_request
	(*ParentNodeResponse)(nil),                           // 14: pb.Parent_node_response
	(*CreateIndirectRelations_Request)(nil),              // 15: pb.Create_indirect_relations_Request
	(*CreateIndirectRelations_Response)(nil),             // 16: pb.Create_indirect_relations_Response
	(*CreateDirectRelations_Request)(nil),                // 17: pb.Create_direct_relations_Request
	(*CreateDirectRelations_Response)(nil),               // 18: pb.Create_direct_relations_Response
	(*CreateIndirectRelationsSingleToMany_Request)(nil),  // 19: pb.Create_indirect_relations_single_to_many_Request
	(*CreateIndirectRelationsSingleToMany_Response)(nil), // 20: pb.Create_indirect_relations_single_to_many_Response
	(*GetNodeWithDirectRelationship_Request)(nil),        // 21: pb.GetNodeWithDirectRelationship_Request
	(*GetNodeWithDirectRelationship_Response)(nil),       // 22: pb.GetNodeWithDirectRelationship_Response
	(*RecursionGetNodeWithDicRelation_Request)(nil),      // 23: pb.Recursion_getNodeWithDicRelation_Request
	(*RecursionGetNodeWithDicRelation_Response)(nil),     // 24: pb.Recursion_getNodeWithDicRelation_Response
}
var file_rpc_transfert_proto_depIdxs = []int32{
	8,  // 0: pb.List_nodes_Response.nodes:type_name -> pb.Node
	8,  // 1: pb.List_nodes_with_relation_Response.nodes:type_name -> pb.Node
	8,  // 2: pb.Delete_relation_request.start_node:type_name -> pb.Node
	8,  // 3: pb.Delete_relation_request.end_nodes:type_name -> pb.Node
	8,  // 4: pb.Parent_node_response.node:type_name -> pb.Node
	8,  // 5: pb.Create_indirect_relations_Request.target_nodes:type_name -> pb.Node
	8,  // 6: pb.Create_indirect_relations_Request.end_nodes:type_name -> pb.Node
	8,  // 7: pb.Create_direct_relations_Request.target_nodes:type_name -> pb.Node
	8,  // 8: pb.Create_direct_relations_Request.end_nodes:type_name -> pb.Node
	8,  // 9: pb.Create_indirect_relations_single_to_many_Request.target_nodes:type_name -> pb.Node
	8,  // 10: pb.GetNodeWithDirectRelationship_Response.node:type_name -> pb.Node
	8,  // 11: pb.Recursion_getNodeWithDicRelation_Response.node:type_name -> pb.Node
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rpc_transfert_proto_init() }
func file_rpc_transfert_proto_init() {
	if File_rpc_transfert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_transfert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeTranfered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHeadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHeadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNodes_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNodes_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNodesWithRelation_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNodesWithRelation_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveFromToDirectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveFromToDirectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIndirectRelations_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIndirectRelations_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDirectRelations_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDirectRelations_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIndirectRelationsSingleToMany_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIndirectRelationsSingleToMany_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeWithDirectRelationship_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeWithDirectRelationship_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecursionGetNodeWithDicRelation_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfert_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecursionGetNodeWithDicRelation_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_transfert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_transfert_proto_goTypes,
		DependencyIndexes: file_rpc_transfert_proto_depIdxs,
		MessageInfos:      file_rpc_transfert_proto_msgTypes,
	}.Build()
	File_rpc_transfert_proto = out.File
	file_rpc_transfert_proto_rawDesc = nil
	file_rpc_transfert_proto_goTypes = nil
	file_rpc_transfert_proto_depIdxs = nil
}
