name: Go CI/CD Workflow with Neo4j

on:
  push:
    branches:
      - main # Adjust this to the branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      neo4j: 
        # Docker Hub image
        image: neo4j

        env:
            NEO4J_AUTH : neo4j/12345678
          
        ports:
            - "7474:7474"  #HTTP port
            - "7687:7687"  #Bolt port

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Set up Go and Initialize Module
      run: |
       
          
          go get  ./...
        
   

    - name: Build
      run: |
           go build -v ./add_user_microservice
           go build -v ./admin_microservice
           go build -v ./delete_microservice
           go build -v ./mlmcli
           go build -v ./transfer_user_microservice
           go build -v ./visualization

    - name: Test
      run: go test -v ./...
